# Generated by Django 6.0.1 on 2026-01-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseService', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
